Updating "Getting Started" tutorial to latest versions
projectsyn/documentation pull request #126
Opened 2021-02-23 10:34 UTC by akosma

This PR provides an update to the "Getting Started" tutorial to the latest versions available of various Syn components.

## Checklist

- [x] Keep pull requests small so they can be easily reviewed.
- [ x Update the documentation.
- [ ] Update the ./CHANGELOG.md.
- [ ] Link this PR to related issues.

2021-02-23 12:07 UTC, tobru commented
I think it would make sense to check the new features from https://github.com/projectsyn/lieutenant-operator/releases/tag/v0.5.0 and see how they could be integrated into to the tutorial to make use of them. @corvus-ch could help you with them.

2021-02-24 13:48 UTC, corvus-ch requested changes

2021-02-24 13:48 UTC, corvus-ch commented on docs/modules/ROOT/pages/tutorials/getting-started.adoc
> +. Now you can access Argo CD by forwarding the port and opening it in your browser with http://localhost:8080. Login with the username `admin` and the password retrieved in the previous step.
The port forward already happend at this point. All that is left, is opening it in the browser. Or did I miss something?

2021-02-24 13:50 UTC, corvus-ch commented
> I think it would make sense to check the new features from https://github.com/projectsyn/lieutenant-operator/releases/tag/v0.5.0 and see how they could be integrated into to the tutorial to make use of them. @corvus-ch could help you with them.

Agree, but let us do this within a change on its own. I would like to see the docs up to date as fast as possible.

2021-02-25 07:37 UTC, tobru commented
> Agree, but let us do this within a change on its own. I would like to see the docs up to date as fast as possible.

Fine be me. Just make sure to not forget to do that later then.

2022-07-01 10:01 UTC, closed without merging

2022-07-04 09:10 UTC, corvus-ch commented
Replaced by  #162.