SDD 0020 - OpenShift Hive
projectsyn/documentation pull request #47
Opened 2020-06-10 09:54 UTC by srueg

WIP

2020-06-10 15:36 UTC, corvus-ch requested changes

2020-06-10 15:36 UTC, corvus-ch commented on docs/modules/SDDs/pages/0020-openshift-hive.adoc
> +* `hive.syn.tools/worker-count` Count of worker nodes to provision
I doubt that scaling is something we should do via Hive. This is something we can do in a more robust way using a component.

From my point of view, it would be find to just go with the defaults for bootstrapping the cluster and then let the component to take over.

So drop `worker-count` and `worker-type`.

2020-06-10 15:36 UTC, corvus-ch commented on docs/modules/SDDs/pages/0020-openshift-hive.adoc
> +* `hive.syn.tools/gcp-project*` GCP project name
Use a footnote instead of a plain `*`.

2020-06-11 06:30 UTC, tobru commented
I think that the ideas of using annotations first is a good thing! Changing this into a proper struct of the CRD later makes it much easier to have a PoC ready.

2020-06-11 06:58 UTC, corvus-ch requested changes

2020-06-11 06:58 UTC, corvus-ch commented on docs/modules/SDDs/pages/0020-openshift-hive.adoc
> +. We would need to duplicate the installation manifests (currently implemented in the xref:0007-lieutenant-management-api.adoc[Lieutenant API]) to create a `SyncSet` out of them
Is the order relevant? I doubt and would use an unordered list here.

2020-06-11 06:58 UTC, corvus-ch commented on docs/modules/SDDs/pages/0020-openshift-hive.adoc
> +An alternative to using a `SyncSet` would be to use the credentials of a provisioned cluster and run a job which installs Syn.
I would not name this an _alternative_ but the suggested/chosen approach.

2020-06-11 13:11 UTC, corvus-ch approved these changes

2020-06-12 13:03 UTC, merged