SDD 0021 - Cluster Catalog Compilation
projectsyn/documentation pull request #62
Opened 2020-06-22 13:53 UTC by srueg

* Rewording of the "Compilation Engine"
* AuthN & AuthZ for the compilation engine

2020-06-22 13:59 UTC, tobru commented
LGTM

2020-06-22 14:19 UTC, corvus-ch requested changes

2020-06-22 14:19 UTC, corvus-ch commented on docs/modules/SDDs/pages/0021-cluster-catalog-compilation.adoc
> +To distribute the load the compilation generates and to follow a decentralized approach, these jobs are run on the same cluster as they compile the catalog for.
That sentences is missing something. Also the decentralization is somewhat redundant with the next sentence.

2020-06-23 12:59 UTC, corvus-ch requested changes

2020-06-23 12:59 UTC, corvus-ch commented on docs/modules/SDDs/pages/0021-cluster-catalog-compilation.adoc
> +By default the compilation engine creates the compile jobs on the respective target clusters (for example via Steward).
```suggestion
Following a decentralized approach, the compilation engine creates the compile jobs on the respective target clusters (for example via Steward).
```

2020-06-23 12:59 UTC, corvus-ch commented on docs/modules/SDDs/pages/0021-cluster-catalog-compilation.adoc
> +With the goal to distribute the load the compilation generates and to follow a decentralized approach.
```suggestion
This removes the need for a central infrastructure which would do nothing most of the time.
```

2020-06-23 13:31 UTC, corvus-ch approved these changes

2020-06-26 09:36 UTC, merged